In [1]:
import cv2
from keras.models import load_model
import numpy as np
from collections import deque
import warnings
warnings.filterwarnings("ignore")


Using TensorFlow backend.


In [2]:

model = load_model("Final.h5")

In [3]:

labels = {0 : "Safe", 1 : "Nude", 2 : "Sexy"}

In [4]:
size = 128
input_vid = "test_video.mp4"
output_vid = "Output/1.avi"

In [5]:
# Mean Subtraction
# mean = np.array([123.68, 116.779, 103.939][::1], dtype="float32")
Q = deque(maxlen=size)

In [6]:
vs = cv2.VideoCapture(input_vid)
writer = None
(W, H) = (None, None)
 
# loop over frames from the video file stream
while True:
    # read the next frame from the file
    (grabbed, frame) = vs.read()
 
    # if the frame was not grabbed, then we have reached the end
    # of the stream
    if not grabbed:
        break
 
    # if the frame dimensions are empty, grab them
    if W is None or H is None:
        (H, W) = frame.shape[:2]
    
    output = frame.copy()
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    frame = frame/255.0
    frame = cv2.resize(frame, (224, 224)).astype("float32")
    
#     frame -= mean
    
    # make predictions on the frame and then update the predictions
    # queue
    preds = model.predict(np.expand_dims(frame, axis=0))[0]
    print(preds)
    Q.append(preds)

    # perform prediction averaging over the current history of
    # previous predictions

    results = np.array(Q).mean(axis=0)
    i = np.argmax(preds)
    label = labels[i]
    # draw the activity on the output frame
    text = "activity: {}:".format(label)
    cv2.putText(output, text, (35, 50), cv2.FONT_HERSHEY_SIMPLEX, 1.25, (0, 255, 0), 5)

    # check if the video writer is None
    if writer is None:
        # initialize our video writer
        fourcc = cv2.VideoWriter_fourcc(*"MJPG")
        writer = cv2.VideoWriter(output_vid, fourcc, 30, (W, H), True)

    # write the output frame to disk
    writer.write(output)

    # show the output image
    cv2.imshow("Output", output)
    key = cv2.waitKey(1) & 0xFF

    # if the `q` key was pressed, break from the loop
    if key == ord("q"):
        break
        
# release the file pointers
print("[INFO] cleaning up...")
# writer.release()
vs.release()

[0.849754   0.01905716 0.13118884]
[0.8299914  0.02269187 0.1473167 ]
[0.84528345 0.02173587 0.1329807 ]
[0.8439097  0.0231526  0.13293771]
[0.82797277 0.02263449 0.14939278]
[0.8096764  0.01587871 0.1744448 ]
[0.7486145  0.0146845  0.23670101]
[0.76623195 0.01376341 0.22000466]
[0.72808576 0.01572528 0.25618896]
[0.7594403  0.01427016 0.22628959]
[0.8865     0.01354907 0.09995095]
[0.87936467 0.01451532 0.10611998]
[0.8808215  0.0145216  0.10465687]
[0.8896761  0.013576   0.09674788]
[0.89054    0.01386045 0.0955996 ]
[0.88407224 0.01469004 0.10123765]
[0.8025503  0.015193   0.18225668]
[0.81288064 0.01494451 0.17217484]
[0.8002058  0.01666361 0.18313058]
[0.7966779  0.01633343 0.18698864]
[0.88912904 0.01356956 0.0973014 ]
[0.9192725  0.01233066 0.06839678]
[0.92292273 0.01194976 0.0651275 ]
[0.92361176 0.01169296 0.06469528]
[0.93205565 0.01035734 0.05758704]
[0.913151   0.01238709 0.07446194]
[0.8263211  0.02027403 0.15340482]
[0.81303453 0.02091617 0.16604926]
[0.84141827 0.017843

[0.96775335 0.01300347 0.0192432 ]
[0.9725424  0.01390871 0.01354885]
[0.97478867 0.01289655 0.0123148 ]
[0.9714938  0.0136876  0.01481861]
[0.9704617  0.0149141  0.01462423]
[0.9805891  0.00944217 0.0099687 ]
[0.982554   0.00779101 0.00965503]
[0.97993326 0.00944089 0.01062585]
[0.9784728  0.01004192 0.01148526]
[0.97865754 0.0103744  0.01096799]
[0.97574425 0.00959875 0.01465693]
[0.9742473  0.00994903 0.0158036 ]
[0.97679216 0.00897775 0.01423016]
[0.9746882  0.01015473 0.01515714]
[0.9730613  0.0109779  0.01596068]
[0.98134977 0.00760152 0.01104871]
[0.97987807 0.00867475 0.01144722]
[0.9796158  0.00856844 0.01181571]
[0.974516   0.00983068 0.01565342]
[0.9755862  0.00934687 0.01506696]
[0.9723413  0.01076088 0.01689779]
[0.9701521  0.01149223 0.01835569]
[0.97326386 0.01042536 0.01631077]
[0.97182626 0.01269581 0.01547789]
[0.9692784  0.01373316 0.0169885 ]
[0.97087896 0.01206204 0.0170589 ]
[0.97358173 0.01146404 0.01495416]
[0.9705669  0.01297719 0.01645584]
[0.9663766  0.015222

[0.78807324 0.05653982 0.15538698]
[0.78989875 0.05608649 0.15401478]
[0.7694976  0.05897886 0.17152351]
[0.7671091  0.05859368 0.17429717]
[0.8706276  0.02645763 0.10291477]
[0.69434404 0.06848148 0.23717448]
[0.68385816 0.07255459 0.2435873 ]
[0.539381   0.08896822 0.3716508 ]
[0.5107894  0.09578992 0.3934207 ]
[0.43617913 0.11158056 0.45224026]
[0.49738678 0.13312392 0.36948934]
[0.4953679  0.1375809  0.36705118]
[0.552479   0.09445135 0.35306957]
[0.59755963 0.0890545  0.3133858 ]
[0.710711   0.07295662 0.21633233]
[0.7975374  0.04138261 0.16108   ]
[0.7782179  0.04235046 0.17943163]
[0.4804201  0.09417914 0.4254008 ]
[0.4599372  0.10016797 0.43989483]
[0.779958   0.05118587 0.1688562 ]
[0.5414654  0.08378759 0.374747  ]
[0.5430013  0.08422398 0.37277472]
[0.6743936  0.0753337  0.25027278]
[0.67735773 0.07355741 0.24908487]
[0.7258958  0.04740367 0.2267005 ]
[0.38640267 0.16656666 0.44703066]
[0.4009183  0.15877907 0.44030267]
[0.49934164 0.13470699 0.36595133]
[0.5201372  0.123279

[0.15324928 0.27133688 0.5754138 ]
[0.15591377 0.27488714 0.5691991 ]
[0.18356419 0.32008985 0.49634597]
[0.08747452 0.2233003  0.6892252 ]
[0.09008414 0.22796273 0.6819531 ]
[0.08181349 0.32738924 0.59079725]
[0.08836604 0.3270445  0.5845895 ]
[0.0800352  0.26244572 0.65751904]
[0.15110527 0.21941395 0.6294808 ]
[0.1644785  0.21385664 0.6216649 ]
[0.18529339 0.15286572 0.66184086]
[0.19254039 0.15396823 0.65349144]
[0.14692184 0.14480434 0.7082738 ]
[0.15947022 0.17683323 0.6636965 ]
[0.15026127 0.16588031 0.6838584 ]
[0.09877384 0.15774299 0.7434832 ]
[0.07831963 0.17221281 0.7494676 ]
[0.08382425 0.14212266 0.7740531 ]
[0.21054955 0.15637988 0.6330706 ]
[0.20914553 0.15286857 0.63798594]
[0.26735055 0.11475559 0.6178939 ]
[0.22868137 0.11983945 0.65147924]
[0.3954979  0.0906667  0.51383543]
[0.25696367 0.09888288 0.6441534 ]
[0.21294284 0.10667161 0.68038553]
[0.27142593 0.072293   0.65628105]
[0.26446503 0.07254402 0.6629909 ]
[0.37793806 0.09155619 0.5305058 ]
[0.61675817 0.075976

[0.9974343  0.00102144 0.00154425]
[9.9777931e-01 8.7363756e-04 1.3470990e-03]
[9.9783128e-01 8.3644886e-04 1.3322864e-03]
[9.9776828e-01 7.2652922e-04 1.5052572e-03]
[9.9726140e-01 9.5064228e-04 1.7879603e-03]
[0.99717253 0.00100094 0.0018266 ]
[9.9735641e-01 8.4925059e-04 1.7943692e-03]
[9.9740666e-01 8.2474528e-04 1.7686621e-03]
[9.9848396e-01 4.7945665e-04 1.0366067e-03]
[9.9777067e-01 7.0764095e-04 1.5217056e-03]
[9.9789989e-01 6.4456876e-04 1.4555826e-03]
[9.9840349e-01 5.6780939e-04 1.0286584e-03]
[9.9839836e-01 5.7356025e-04 1.0280849e-03]
[9.9812967e-01 6.5756851e-04 1.2128697e-03]
[9.9736977e-01 6.7849725e-04 1.9516929e-03]
[9.9707723e-01 8.0623687e-04 2.1165826e-03]
[9.9740404e-01 7.2834699e-04 1.8675509e-03]
[9.9749362e-01 6.8867096e-04 1.8177128e-03]
[9.9757212e-01 5.6204479e-04 1.8658983e-03]
[9.9800187e-01 5.1579432e-04 1.4824383e-03]
[9.9806815e-01 5.2024075e-04 1.4115173e-03]
[9.9718612e-01 6.9139164e-04 2.1225212e-03]
[9.971975e-01 6.912403e-04 2.111204e-03]
[0.996656

[0.92712915 0.03063517 0.04223572]
[0.92968047 0.03658502 0.03373444]
[0.9324991  0.03574032 0.03176059]
[0.9059843  0.04998501 0.04403074]
[0.88503325 0.05680936 0.05815735]
[0.8938843  0.05046658 0.05564912]
[0.9111242  0.03710859 0.05176717]
[0.9166341  0.03471153 0.04865431]
[0.8320644  0.09175663 0.07617899]
[0.9121465  0.03780549 0.05004808]
[0.90683675 0.04097905 0.05218419]
[0.85015225 0.06083629 0.08901139]
[0.8527255  0.05779076 0.08948372]
[0.8771451  0.06077624 0.06207866]
[0.9125013  0.03403475 0.05346392]
[0.90922844 0.03543113 0.05534042]
[0.9079859  0.0431996  0.04881444]
[0.9092126  0.04153283 0.04925454]
[0.9439554  0.02346954 0.03257505]
[0.94000304 0.03272096 0.02727589]
[0.941936   0.03144608 0.02661789]
[0.94178575 0.02993033 0.02828398]
[0.9411254  0.03016146 0.02871316]
[0.95653987 0.01914941 0.02431078]
[0.9513512  0.01550753 0.03314121]
[0.95023423 0.01703641 0.03272938]
[0.92726094 0.0205512  0.0521878 ]
[0.92435503 0.02151579 0.05412918]
[0.90208465 0.029167

[0.02825198 0.02278892 0.9489591 ]
[0.0208001  0.02673161 0.9524683 ]
[0.01613905 0.01101443 0.97284645]
[0.01476273 0.01021721 0.97502   ]
[0.01414351 0.00989989 0.9759567 ]
[0.01268795 0.0089597  0.9783523 ]
[0.02693697 0.01783222 0.95523083]
[0.06107234 0.02872677 0.9102009 ]
[0.06060587 0.02853697 0.91085714]
[0.06003578 0.02819341 0.9117708 ]
[0.06117586 0.02914918 0.909675  ]
[0.06998021 0.03939545 0.89062434]
[0.10537197 0.05154654 0.84308153]
[0.10692613 0.05193868 0.8411352 ]
[0.10476822 0.05170397 0.8435278 ]
[0.10611297 0.05203355 0.84185344]
[0.06105556 0.03663089 0.9023136 ]
[0.13673924 0.06613111 0.79712963]
[0.13513988 0.06573597 0.7991242 ]
[0.13514178 0.0662392  0.79861903]
[0.13649979 0.06618727 0.7973129 ]
[0.09916429 0.0492319  0.85160375]
[0.11044968 0.08201219 0.8075381 ]
[0.11133294 0.08376079 0.8049063 ]
[0.10971685 0.0843065  0.8059766 ]
[0.11284877 0.08688632 0.8002649 ]
[0.36443022 0.09353106 0.54203874]
[0.37875247 0.09010687 0.5311407 ]
[0.3685812  0.092942

[0.11606343 0.1929977  0.6909389 ]
[0.12197048 0.24908161 0.6289479 ]
[0.12580879 0.25365934 0.62053186]
[0.12829545 0.17211382 0.69959074]
[0.09042794 0.17975062 0.7298214 ]
[0.09663723 0.17699784 0.726365  ]
[0.08446436 0.1696238  0.74591184]
[0.0721764  0.16514203 0.76268154]
[0.11226481 0.16567641 0.72205883]
[0.12601028 0.19532464 0.67866504]
[0.13313569 0.20176356 0.6651007 ]
[0.1304552  0.20572321 0.6638216 ]
[0.13218968 0.20696014 0.6608502 ]
[0.11861935 0.20683908 0.67454153]
[0.12148327 0.20385505 0.6746617 ]
[0.11867435 0.19293627 0.68838936]
[0.11646152 0.17281142 0.7107271 ]
[0.11264976 0.18144423 0.705906  ]
[0.13107623 0.18062942 0.68829435]
[0.13791408 0.14886433 0.7132216 ]
[0.13641979 0.14534493 0.71823525]
[0.12607676 0.1402036  0.73371965]
[0.10566842 0.13759196 0.75673956]
[0.09410442 0.11765406 0.7882415 ]
[0.137892   0.1583693  0.70373875]
[0.12663116 0.14236058 0.7310083 ]
[0.13478099 0.1350004  0.7302186 ]
[0.13808039 0.13224429 0.7296754 ]
[0.18868944 0.158970

[0.1247591  0.23195057 0.64329034]
[0.1396925  0.22128691 0.63902056]
[0.13719472 0.22218557 0.6406197 ]
[0.11332264 0.2023139  0.6843635 ]
[0.13158901 0.2518267  0.61658424]
[0.1287621  0.23979847 0.63143945]
[0.13392232 0.22785014 0.6382276 ]
[0.13866022 0.22397415 0.63736564]
[0.1471027  0.21463674 0.6382606 ]
[0.12220458 0.19998233 0.6778131 ]
[0.11913088 0.20691751 0.67395157]
[0.13419525 0.17464185 0.6911629 ]
[0.14020616 0.1825233  0.67727053]
[0.1406932  0.16465463 0.6946522 ]
[0.18943311 0.25278896 0.55777794]
[0.18972419 0.25228825 0.5579875 ]
[0.17422967 0.26539412 0.5603762 ]
[0.17660072 0.2693207  0.5540786 ]
[0.14543924 0.29063344 0.5639273 ]
[0.13396662 0.23431069 0.6317227 ]
[0.14047888 0.239978   0.61954314]
[0.13572598 0.23093417 0.6333399 ]
[0.12732382 0.21435116 0.658325  ]
[0.1993772  0.29740286 0.50321996]
[0.15808192 0.25474176 0.5871763 ]
[0.1592937 0.2248013 0.615905 ]
[0.14356786 0.18535043 0.6710817 ]
[0.1587346  0.18921553 0.65204984]
[0.12716398 0.22164655 